export const GET_DON_ADMIN="GET_DON_ADMIN"
export const FAIL_DON_ADMIN="FAIL_DON_ADMIN"
export const LOAD_DON_ADMIN="LOAD_DON_ADMIN"

export const SIGN_IN_ADMIN="SIGN_IN_ADMIN"
export const SIGN_UP_ADMIN="SIGN_UP_ADMIN"

export const LOG_OUT_ADMIN="LOG_OUT_ADMIN"
export const LOAD_AUTH_ADMIN="LOAD_AUTH_ADMIN"
export const FAIL_AUTH_ADMIN="FAIL_AUTH_ADMIN"

export const GET_USER_ADMIN="GET_USER_ADMIN"
export const FAIL_USER_ADMIN="FAIL_USER_ADMIN"
export const LOAD_USER_ADMIN="LOAD_USER_ADMIN"